# -*- coding: utf-8 -*-
"""AI Text Generator using Markov Chains.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eT_begr8TPuurfHKy73lPUU6M1bajxpU
"""

!pip install nltk
!pip install spacy
!pip install markovify

!python -m spacy download en_core_web_sm

import re
import nltk
import spacy
import markovify
import warnings

from nltk.corpus import gutenberg

warnings.filterwarnings("ignore")

nltk.download("gutenberg")

nlp = spacy.load("en_core_web_sm")

hamlet = gutenberg.raw("shakespeare-hamlet.txt")
macbeth = gutenberg.raw("shakespeare-macbeth.txt")
caesar = gutenberg.raw("shakespeare-caesar.txt")

def clean_text(text):
    text = re.sub(r"\[[^\]]*\]", " ", text)   # remove [stage directions]
    text = re.sub(r"\s+", " ", text)         # remove extra spaces
    text = re.sub(r"[^a-zA-Z.?!' ]", " ", text)  # keep only clean chars
    text = re.sub(r"\s+", " ", text)
    return text.strip()

hamlet = clean_text(hamlet)
macbeth = clean_text(macbeth)
caesar = clean_text(caesar)

shakespeare_text = hamlet + " " + macbeth + " " + caesar

doc = nlp(shakespeare_text)

sentences = [
    sent.text.strip()
    for sent in doc.sents
    if len(sent.text.strip().split()) > 4
]

clean_corpus = " ".join(sentences)

model = markovify.Text(clean_corpus, state_size=3)

def generate_text(model, n=5):
    for i in range(n):
        sentence = model.make_sentence(tries=200)
        if sentence is None:
            sentence = model.make_short_sentence(120, tries=200)
        print(sentence)

generate_text(model, 5)

for i in range(5):
    print(model.make_short_sentence(120, tries=200))